on: [push, pull_request]

name: Pull Request Checks

jobs:
  build:
    name: Checkup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '^1.17.4'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'latest'
      - name: Run Tests
        id: run_tests
        run: make test
